name: CI for Python 3.11.3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.3
    - name: Install Dependencies and Package
      run: |
        make install
    - name: Linting
      run: |
        make lint
    - name: Unit Test
      run: |
        make test